### ISSUE TITLE
自定义地图练级选择阵型 复纵阵， MaaJR选择为单横阵，其他阵型没问题

### ISSUE THREAD

**Issue by ChLe6260** [Saratoga-Official/MaaJR#1]
模拟器：MUMU12
分辨率：1600*900
![image](https://github.com/user-attachments/assets/27b93efe-3c9a-4e7d-b4ae-fbe3e98943ab)

[maa.log](https://github.com/user-attachments/files/17303851/maa.log)

**Comment by Saratoga-Official** [comment]
单横是默认值，没看出来什么原因，可能是默认没根据选项改？至于分辨率我是在1600*900下做的截图识别，别的分辨率没做测试，应该不是分辨率原因，大概偶然现象？

**Comment by Saratoga-Official** [comment]
知道什么原因了，将在V2.0.3版本修复
