### ISSUE TITLE
能否加一个战况选择功能

### ISSUE THREAD

**Issue by senyamiku1101** [Saratoga-Official/MaaJR#6]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的建议未被提及

### 说说你遇到的问题？

8章之后的部分点位有战况选择，现在软件运行到有战况的时候就会无法进行下一步，能不能增加一个自动选择战况的功能？

**Comment by Saratoga-Official** [comment]
能具体说一下那些点有战况吗，我没遇到过不知道应该加在哪个地方

**Comment by senyamiku1101** [comment]
比如8-2b点，进去过后会有五个战况选择

**Comment by senyamiku1101** [comment]
> 能具体说一下那些点有战况吗，我没遇到过不知道应该加在哪个地方

比如8-2b点，进去过后会有五个战况选择

**Comment by senyamiku1101** [comment]
就想这样一个界面

**Comment by senyamiku1101** [comment]
> 能具体说一下那些点有战况吗，我没遇到过不知道应该加在哪个地方

![image](https://github.com/user-attachments/assets/f7b57a7b-c490-406f-9f2f-7582a7ede6f2)
就像这样

**Comment by Saratoga-Official** [comment]
看到了，查了下wiki
先做个随便选的吧，这种特殊关卡的不适合单独做选项

**Comment by senyamiku1101** [comment]
> 看到了，查了下wiki 先做个随便选的吧，这种特殊关卡的不适合单独做选项

可以，感谢大佬
