### ISSUE TITLE
无消耗1-1 卡在自动换船处，不进行‘排列顺序’操作

### ISSUE THREAD

**Issue by huizhu963** [Saratoga-Official/MaaJR#8]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

无消耗1-1 卡在自动换船处，不进行‘排列顺序’操作

### Version

v2.3.0

### 日志文件

[maa.log](https://github.com/user-attachments/files/18139531/maa.log)

### 配置信息

win 11 , mumu 12 模拟器

**Comment by Saratoga-Official** [comment]
这块下版本换一个ocr识别，可能模板识别不太行

**Comment by huizhu963** [comment]
感谢作者大大

萨拉托加 ***@***.***> 于2024年12月15日周日 16:03写道：
